image: rootproject/root-ubuntu16

stages:
  - run

install:
  stage: run
  script:
    - $(root-config --cxx) $(root-config --cflags) foo.cpp -c -o foo.o -Wall -Wextra
    - $(root-config --cxx) foo.o $(root-config --libs) -o foo
